version: '3.7'

services:
  backend:
    build: ./backend
    image: kitchen/backend:1.0
    volumes:
      - "./backend/:/app/"
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=hayashis-kitchen
